In [19]:
import pandas as pd
from glob import glob

# --------------------------------------------------------------
# Read single CSV file
# --------------------------------------------------------------

In [20]:

single_file_acc = pd.read_csv("D:/Projects/Fitness Tracker/data/raw/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv")

single_file_gyro = pd.read_csv("D:/Projects/Fitness Tracker/data/raw/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv")

# --------------------------------------------------------------
# List all data in data/raw/MetaMotion
# --------------------------------------------------------------

In [21]:


files = glob("D:/Projects/Fitness Tracker/data/raw/MetaMotion/*.csv")
len(files)

187

# --------------------------------------------------------------
# Extract features from filename
# --------------------------------------------------------------

In [22]:


data_path = "D:/Projects/Fitness Tracker/data/raw/MetaMotion"
f = files[1]

participant = f.split("-")[0].replace(data_path, "").lstrip("\\")

label = f.split("-")[1]

category = f.split("-")[2].rstrip("123").rstrip('_Metawear_2019')

In [23]:
df = pd.read_csv(f)

df["participant"] = participant
df["label"] = label
df["category"] = category

In [24]:
participant, label, category

('A', 'bench', 'heavy')

In [25]:
df

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category
0,1547219408351,2019-01-11T16:10:08.351,0.00,0.122,-5.488,-3.841,A,bench,heavy
1,1547219408391,2019-01-11T16:10:08.391,0.04,2.195,-9.695,-0.610,A,bench,heavy
2,1547219408431,2019-01-11T16:10:08.431,0.08,2.622,-8.110,-4.024,A,bench,heavy
3,1547219408471,2019-01-11T16:10:08.471,0.12,1.951,-4.695,-4.634,A,bench,heavy
4,1547219408511,2019-01-11T16:10:08.511,0.16,1.524,-2.561,-2.500,A,bench,heavy
...,...,...,...,...,...,...,...,...,...
409,1547219424711,2019-01-11T16:10:24.711,16.36,2.195,-1.402,4.268,A,bench,heavy
410,1547219424751,2019-01-11T16:10:24.751,16.40,4.451,-1.220,0.244,A,bench,heavy
411,1547219424791,2019-01-11T16:10:24.791,16.44,7.195,-4.329,6.524,A,bench,heavy
412,1547219424831,2019-01-11T16:10:24.831,16.48,8.963,-1.037,-0.366,A,bench,heavy
413,1547219424871,2019-01-11T16:10:24.871,16.52,-3.476,2.134,-5.305,A,bench,heavy

# ------------------------------------
# Read all files
# --------------------------------------------------------------

In [26]:


acc_df = pd.DataFrame()
gyr_df = pd.DataFrame()

acc_set = 1
gyr_set = 1

for f in files:
    participant = f.split("-")[0].replace(data_path, "").lstrip("\\")
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip('_Metawear_2019').rstrip("_MetaW").rstrip("123")
    
    df = pd.read_csv(f)
    df["participant"] = participant
    df["label"] = label
    df["category"] = category
    
    if "Accelerometer" in f:
        df["set"] = acc_set
        acc_set += 1
        acc_df = pd.concat([acc_df, df])
        
    if "Gyroscope" in f:
        df["set"]= gyr_set
        gyr_set += 1
        gyr_df = pd.concat([gyr_df, df])
        
        
acc_df[acc_df["set"]==10]

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
0,1547221285010,2019-01-11T16:41:25.010,0.00,-0.107,0.948,-0.004,A,ohp,heavy,10
1,1547221285090,2019-01-11T16:41:25.090,0.08,-0.137,1.417,-0.084,A,ohp,heavy,10
2,1547221285170,2019-01-11T16:41:25.170,0.16,-0.220,1.425,-0.054,A,ohp,heavy,10
3,1547221285250,2019-01-11T16:41:25.250,0.24,-0.221,1.138,-0.027,A,ohp,heavy,10
4,1547221285330,2019-01-11T16:41:25.330,0.32,-0.254,0.940,-0.024,A,ohp,heavy,10
...,...,...,...,...,...,...,...,...,...,...
153,1547221297250,2019-01-11T16:41:37.250,12.24,-0.185,0.926,-0.044,A,ohp,heavy,10
154,1547221297330,2019-01-11T16:41:37.330,12.32,-0.136,0.678,-0.048,A,ohp,heavy,10
155,1547221297410,2019-01-11T16:41:37.410,12.40,-0.097,0.739,-0.070,A,ohp,heavy,10
156,1547221297490,2019-01-11T16:41:37.490,12.48,-0.155,1.021,-0.043,A,ohp,heavy,10
157,1547221297570,2019-01-11T16:41:37.570,12.56,-0.160,0.866,-0.014,A,ohp,heavy,10

# --------------------------------------------------------------
# Working with datetimes
# --------------------------------------------------------------

In [27]:
acc_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23578 entries, 0 to 241
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   epoch (ms)    23578 non-null  int64
 1   time (01:00)  23578 non-null  object
 2   elapsed (s)   23578 non-null  float64
 3   x-axis (g)    23578 non-null  float64
 4   y-axis (g)    23578 non-null  float64
 5   z-axis (g)    23578 non-null  float64
 6   participant   23578 non-null  object
 7   label         23578 non-null  object
 8   category      23578 non-null  object
 9   set           23578 non-null  int64
dtypes: float64(4), int64(2), object(4)
memory usage: 2.0+ MB

In [28]:
acc_df.info()
pd.to_datetime(df["epoch (ms)"], unit="ms")

acc_df.index = pd.to_datetime(acc_df["epoch (ms)"],unit="ms")
gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"],unit="ms")

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23578 entries, 0 to 241
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   epoch (ms)    23578 non-null  int64
 1   time (01:00)  23578 non-null  object
 2   elapsed (s)   23578 non-null  float64
 3   x-axis (g)    23578 non-null  float64
 4   y-axis (g)    23578 non-null  float64
 5   z-axis (g)    23578 non-null  float64
 6   participant   23578 non-null  object
 7   label         23578 non-null  object
 8   category      23578 non-null  object
 9   set           23578 non-null  int64
dtypes: float64(4), int64(2), object(4)
memory usage: 2.0+ MB

In [29]:
del acc_df["epoch (ms)"]
del acc_df["time (01:00)"]
del acc_df["elapsed (s)"]
del gyr_df["elapsed (s)"]
del gyr_df["epoch (ms)"]
del gyr_df["time (01:00)"]

# --------------------------------------------------------------
# Turn into function
# --------------------------------------------------------------

In [30]:
files = glob("D:/Projects/Fitness Tracker/data/raw/MetaMotion/*.csv")
len(files)

def read_data_from_files(files):
    acc_df = pd.DataFrame()
    gyr_df = pd.DataFrame()

    acc_set = 1
    gyr_set = 1

    for f in files:
        participant = f.split("-")[0].replace(data_path, "").lstrip("\\")
        label = f.split("-")[1]
        category = f.split("-")[2].rstrip('_Metawear_2019').rstrip("_MetaW").rstrip("123")
        
        df = pd.read_csv(f)
        df["participant"] = participant
        df["label"] = label
        df["category"] = category
        
        if "Accelerometer" in f:
            df["set"] = acc_set
            acc_set += 1
            acc_df = pd.concat([acc_df, df])
            
        if "Gyroscope" in f:
            df["set"]= gyr_set
            gyr_set += 1
            gyr_df = pd.concat([gyr_df, df])
            
    acc_df.index = pd.to_datetime(acc_df["epoch (ms)"],unit="ms")
    gyr_df.index = pd.to_datetime(gyr_df["epoch (ms)"],unit="ms")
    
    del acc_df["epoch (ms)"]
    del acc_df["time (01:00)"]
    del acc_df["elapsed (s)"]
    del gyr_df["elapsed (s)"]
    del gyr_df["epoch (ms)"]
    del gyr_df["time (01:00)"]
    
    return acc_df, gyr_df
        
acc_df, gyr_df = read_data_from_files(files)

# --------------------------------------------------------------
# Merging datasets
# --------------------------------------------------------------

In [31]:
data_merged = pd.concat([acc_df.iloc[:,:3], gyr_df], axis=1)
data_merged

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
data_merged.dropna()

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,2.622,-8.110,-4.024,A,bench,heavy,1.0
2019-01-11 15:10:08.511,0.000,0.961,-0.069,1.524,-2.561,-2.500,A,bench,heavy,1.0
2019-01-11 15:10:08.591,0.001,0.974,-0.087,1.707,-5.366,0.915,A,bench,heavy,1.0
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,2.683,-4.146,-1.220,A,bench,heavy,1.0
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,1.524,0.610,-3.171,A,bench,heavy,1.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-15 19:04:25.561,0.369,0.591,0.761,11.220,-5.061,-5.061,A,squat,heavy,24.0
2019-01-15 19:04:25.641,0.387,0.566,0.776,3.963,-2.988,-0.793,A,squat,heavy,24.0
2019-01-15 19:04:25.721,0.361,0.574,0.680,15.305,-3.293,-0.671,A,squat,heavy,24.0
2019-01-15 19:04:25.801,0.353,0.583,0.635,30.366,-0.122,-4.573,A,squat,heavy,24.0
2019-01-15 19:04:25.881,0.359,0.605,0.678,14.756,-6.585,-2.378,A,squat,heavy,24.0

In [33]:
data_merged.columns = [
    "acc_x",
    "acc_y",
    "acc_z",
    "gyr_x",
    "gyr_y",
    "gyr_z",
    "participant",
    "label",
    "category",
    "set"
]
data_merged

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# --------------------------------------------------------------
# Resample data (frequency conversion)
# --------------------------------------------------------------

### Accelerometer:    12.500HZ
### Gyroscope:        25.000Hz

In [34]:
1/25, 1/12
data_merged[:1000].resample(rule="S").mean()

C:\Users\ibrah\AppData\Local\Temp\ipykernel_8260\1480587412.py:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  data_merged[:1000].resample(rule="S").mean()

,acc_x,acc_y,acc_z,gyr_x,gyr_y,gyr_z,set
epoch (ms),,,,,,,
2019-01-11 15:08:04,NaN,NaN,NaN,-9.695500,-1.798500,4.573500,30.0
2019-01-11 15:08:05,-0.002222,0.969333,-0.071222,1.007320,-0.731720,-0.399960,30.0
2019-01-11 15:08:06,-0.099231,0.899462,-0.163846,6.978040,2.417120,-11.256200,30.0
2019-01-11 15:08:07,-0.204750,1.055917,-0.156333,1.317040,-2.083000,2.248840,30.0
2019-01-11 15:08:08,-0.079462,0.920462,-0.085692,-9.826840,-4.697560,8.356160,30.0
...,...,...,...,...,...,...,...
2019-01-11 15:10:18,-0.159308,1.022154,-0.169462,-4.687760,-0.229240,-2.634160,1.0
2019-01-11 15:10:19,-0.136167,0.938417,-0.129417,-4.741400,1.731800,14.529320,1.0
2019-01-11 15:10:20,-0.003769,0.938615,-0.106846,6.426880,-5.836560,-4.370720,1.0
2019-01-11 15:10:21,-0.152750,1.017750,-0.182167,1.597440,-6.397600,-5.312120,1.0
2019-01-11 15:10:22,-0.211571,0.890857,-0.174000,4.668929,4.703786,-2.613214,1.0

In [35]:
sampling = {
    "acc_x": "mean",
    "acc_y": "mean",
    "acc_z": "mean",
    "gyr_x": "mean",
    "gyr_y": "mean",
    "gyr_z": "mean",
    "participant": "last",
    "label": "last",
    "category": "last",
    "set": "last",
}
data_merged.columns
data_merged[:1000].resample(rule="200ms").apply(sampling)

days = [g for n, g in data_merged.groupby(pd.Grouper(freq="D"))]

data_resampled = pd.concat([df.resample(rule=("200ms")).apply(sampling).dropna() for df in days])


data_resampled["set"] =data_resampled["set"].astype("int")
data_resampled.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9009 entries, 2019-01-11 15:08:05.200000 to 2019-01-20 17:33:27.800000
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acc_x        9009 non-null   float64
 1   acc_y        9009 non-null   float64
 2   acc_z        9009 non-null   float64
 3   gyr_x        9009 non-null   float64
 4   gyr_y        9009 non-null   float64
 5   gyr_z        9009 non-null   float64
 6   participant  9009 non-null   object
 7   label        9009 non-null   object
 8   category     9009 non-null   object
 9   set          9009 non-null   int32
dtypes: float64(6), int32(1), object(3)
memory usage: 739.0+ KB

# --------------------------------------------------------------
# Export dataset
# --------------------------------------------------------------

In [36]:
data_resampled.to_pickle("../../data/interim/01_data_processed.pkl")